opencost:
  prometheus:
    internal:
      namespaceName: default
      serviceName: prometheus-kube-prometheus-prometheus
      port: 9090

  dataRetention:
    dailyResolutionDays: 30  # default: 15

  # exporter:
  #   defaultClusterId: microk8s
  #   replicas: 1
  #   resources:
  #     requests:
  #       cpu: "10m"
  #       memory: "55Mi"
  #     limits:
  #       memory: "1Gi"
  #   persistence:
  #     enabled: true
  #     storageClass: "csi-cinder-high-speed"  # adjust based on your environment
  #     accessMode: ReadWriteOnce
  #     size: 5Gi

  customPricing:
    enabled: true
    costModel:
      description: Modified pricing configuration.
      CPU: 0.031611
      spotCPU: 0.006655
      RAM: 0.004237
      spotRAM: 0.000892
      GPU: 0.95
      storage: 0.00005479452
      zoneNetworkEgress: 0.01
      regionNetworkEgress: 0.01
      internetNetworkEgress: 0.143
      spotLabel: ""
      spotLabelValue: ""
      awsServiceKeyName: ""
      awsServiceKeySecret: ""
      awsSpotDataRegion: ""
      awsSpotDataBucket: ""
      awsSpotDataPrefix: ""
      athenaBucketName: ""
      athenaRegion: ""
      athenaDatabase: ""
      athenaTable: ""

  metrics:
    kubeStateMetrics:
      emitKsmV1Metrics: false
      emitKsmV1MetricsOnly: false
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus

  ui:
    enabled: true