extraEnv:
  - name: DCGM_EXPORTER_DEBUG
    value: "false"
  - name: DCGM_EXPORTER_INTERVAL
    value: "1000"

serviceMonitor:
  enabled: true
  interval: 1s

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nvidia.com/gpu.present
          operator: In
          values:
          - "true"
