apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-analyzer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-analyzer
  template:
    metadata:
      labels:
        app: gpu-analyzer
    spec:
      containers:
        - name: analyzer
          image: maxireis/knative-reevaluation@sha256:f32e6ed1bfe8702beedcfee7df3ffe8756827350aacf6faa960eeaadb0e26521
          imagePullPolicy: Always
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-kube-prometheus-prometheus:9090"
