apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-analyzer
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-analyzer
  template:
    metadata:
      labels:
        app: gpu-analyzer
    spec:
      containers:
        - name: analyzer
          image: maxireis/knative-reevaluation@sha256:983eab0544275a30758e7b4ae461a737174156e33a297f72c237fe80a49c7687
          imagePullPolicy: Always
          env:
            # Prometheus configuration
            - name: PROMETHEUS_URL
              value: "http://prometheus-kube-prometheus-prometheus:9090"

            # Timing configuration
            - name: INTERVAL_SECONDS
              value: "60"
            - name: WINDOW_SECONDS
              value: "30m"

            # Logging configuration
            - name: LOG_LEVEL
              value: "DEBUG"
